# Generated by Django 3.2.6 on 2021-08-21 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=255)),
                ('employees', models.CharField(default='NA', max_length=255)),
                ('linkedin_url', models.CharField(max_length=255, unique=True)),
                ('domain', models.CharField(default='NA', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Companies Data',
            },
        ),
        migrations.CreateModel(
            name='UsersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=255)),
                ('title', models.CharField(default='NA', max_length=255)),
                ('location', models.CharField(default='NA', max_length=255)),
                ('linkedin_url', models.CharField(max_length=255, unique=True)),
                ('valid_emails', models.CharField(default='NA', max_length=255)),
                ('exported', models.CharField(default='NA', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapData.companies')),
            ],
            options={
                'verbose_name_plural': 'Users Data',
            },
        ),
    ]
