# Generated by Django 3.2.6 on 2021-08-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='followers',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='companies',
            name='industry',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='companies',
            name='location',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='companies',
            name='tagline',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
