# Generated by Django 3.2.6 on 2021-08-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapData', '0002_auto_20210821_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='data_scrapped',
            field=models.CharField(default='No', max_length=50),
        ),
    ]
