# Generated by Django 3.2.6 on 2021-08-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapData', '0003_companies_data_scrapped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='valid_emails',
            field=models.TextField(default='NA'),
        ),
    ]
